branches:
  only:
    - master

dist: trusty
sudo: required

language: node_js

node_js:
  - "12.18.4"

env:
  global:
    - GH_REPO=https://${GH_TOKEN}@github.com/herotc/shadowlands-prepatch.herodamage.com.git
    - GH_SOURCE_BRANCH=master
    - GH_TARGET_BRANCH=gh-pages
    - NODE_ENV=production
    - BASE_URL=https://shadowlands-prepatch.herodamage.com
    # The number of file changes required to deploy, put the number of files generated on build + 1
    - DEPLOY_THRESHOLD=1

cache:
  directories:
    - "node_modules"

before_install:
  - node --version
  - npm --version

install:
  # npm ci may not work due to npm ls failing whenever optional dependencies are in the package-lock.json
  # but cannot be installed (due to linux/osx/windows different requirements)
  - npm install --production=false # production is set to false to install devDependencies required to build

before_script:
  - chmod +x ./scripts/ci/build.sh
  - chmod +x ./scripts/ci/deploy.sh

script:
  - travis_wait 50 ./scripts/ci/build.sh
  - travis_wait 50 ./scripts/ci/deploy.sh
